# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agora-l402',
                'doc_host': 'https://Fewsats.github.io',
                'git_url': 'https://github.com/Fewsats/agora-l402',
                'lib_path': 'agora_l402'},
  'syms': { 'agora_l402.core': { 'agora_l402.core.ProductCard': ('core.html#productcard', 'agora_l402/core.py'),
                                 'agora_l402.core.add_to_cart': ('core.html#add_to_cart', 'agora_l402/core.py'),
                                 'agora_l402.core.create_cart': ('core.html#create_cart', 'agora_l402/core.py'),
                                 'agora_l402.core.create_order': ('core.html#create_order', 'agora_l402/core.py'),
                                 'agora_l402.core.get_product_detail': ('core.html#get_product_detail', 'agora_l402/core.py'),
                                 'agora_l402.core.refresh_token': ('core.html#refresh_token', 'agora_l402/core.py'),
                                 'agora_l402.core.search_trial': ('core.html#search_trial', 'agora_l402/core.py'),
                                 'agora_l402.core.text_search': ('core.html#text_search', 'agora_l402/core.py'),
                                 'agora_l402.core.track_order': ('core.html#track_order', 'agora_l402/core.py')}}}
